version: '3'

# Base tasks that can be included by any environment
# These provide common functionality like setup, clean, help, etc.

tasks:
  setup:
    desc: "Base setup - creates virtual environment and basic structure"
    cmds:
      - echo "Creating virtual environment..."
      - python3 -m venv venv
      - echo "Activating virtual environment..."
      - source venv/bin/activate
      - echo "Base setup completed!"

  clean:
    desc: "Base clean - removes build artifacts and temporary files"
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf build/
      - rm -rf dist/
      - rm -rf *.egg-info/
      - rm -rf __pycache__/
      - rm -rf .pytest_cache/
      - rm -rf .coverage
      - rm -rf htmlcov/
      - echo "Base clean completed!"

  help:
    desc: "Base help - shows available tasks and their descriptions"
    cmds:
      - echo "Available base tasks:"
      - echo "  setup  - Create virtual environment and basic structure"
      - echo "  clean  - Remove build artifacts and temporary files"
      - echo "  help   - Show this help message"
      - echo ""
      - echo "Additional tasks may be available from included templates."

  status:
    desc: "Base status - shows environment status and configuration"
    cmds:
      - echo "Environment Status:"
      - python3 --version
      - |
        if [ -d "venv" ]; then
          echo "  Virtual environment: Active"
        else
          echo "  Virtual environment: Not created"
        fi
      - pwd
      - task --version

  init:
    desc: "Base init - initializes a new environment with basic structure"
    deps: [setup]
    cmds:
      - echo "Initializing environment..."
      - mkdir -p requirements
      - mkdir -p scripts
      - mkdir -p config
      - mkdir -p tests
      - echo "Environment initialized!"

  reset:
    desc: "Base reset - completely resets the environment (clean + setup)"
    deps: [clean, setup]
    cmds:
      - echo "Environment reset completed!"
