component:
  name: "aiailint"
  type: "tool"
  language: "python"
  description: "AIAI Script validation tool"

dependencies:
  production:
    - "pyyaml>=6.0"
    - "jsonschema>=4.0"
  development:
    - "pytest>=7.0"
    - "black>=23.0"
    - "flake8>=6.0"
    - "mypy>=1.0"
    - "pytest-cov>=4.0"
    - "tox>=4.0"

targets:
  setup:
    description: "Setup development environment"
    commands:
      - "python3 -m venv venv"
      - "source venv/bin/activate && pip install -r requirements/requirements-dev.txt"
      - "pip install -e ../../../aiailint/"
  
  test:
    description: "Run tests"
    commands:
      - "source venv/bin/activate && pytest tests/ --cov=aiailint"
    depends_on: ["setup"]
  
  build:
    description: "Build package"
    commands:
      - "source venv/bin/activate && python -m build"
    depends_on: ["test"]
  
  quality:
    description: "Run quality checks"
    commands:
      - "source venv/bin/activate && black aiailint/"
      - "source venv/bin/activate && flake8 aiailint/"
      - "source venv/bin/activate && mypy aiailint/"
    depends_on: ["setup"]
  
  deploy:
    description: "Deploy component"
    commands:
      - "source venv/bin/activate && python setup.py sdist bdist_wheel"
      - "scp dist/*.whl {{.REMOTE_USER}}@{{.REMOTE_HOST}}:{{.REMOTE_PATH}}/"
      - "ssh {{.REMOTE_USER}}@{{.REMOTE_HOST}} 'cd {{.REMOTE_PATH}} && pip install *.whl'"
    depends_on: ["build"]
  
  clean:
    description: "Clean environment"
    commands:
      - "rm -rf venv"
      - "rm -rf build/"
      - "rm -rf dist/"
      - "rm -rf *.egg-info/"
  
  help:
    description: "Show available tasks"
    commands:
      - "task --list"
