build_tool: "task"  # Can be: task, just, make, custom
tool_config:
  task:
    command: "task"
    file: "Taskfile.yml"
  just:
    command: "just"
    file: "Justfile"
  make:
    command: "make"
    file: "Makefile"
  custom:
    command: "python3"
    file: "custom_deploy.py"
